using UnityEngine;
using UnityEngine.UI;

public class LanguageMenu : MonoBehaviour
{
    public Menu menu;
    [Header("TextMenu")]
    public Text startext;
    public Text starttext;
    public Text optionstext;
    public Text exittext;
    public Text deletealltext;
    public Text musictext;
    public Text deleteall2text;
    public Text yestext;
    public Text yes2text;
    public Text notext;
    public Text no2text;
    public Text exit2text;
    public Text QRtext;
    public Text selectlanguagebut;
    public Text loses;
    public Text swipetext;
    public Text bye;

    public void Awake()
    {
        SetLanguage();
    }

    public void SetLanguage()
    {
        switch (PlayerPrefs.GetInt("Language"))
        {
            case 0: //Английский
                startext.text = "Stars: ";
                loses.text = "Losses: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "Start";
                optionstext.text = "Options";
                exittext.text = "Exit";
                exit2text.text = "Exit?";
                deletealltext.text = "Delete All";
                deleteall2text.text = "Delete All?";
                musictext.text = "Music";
                yestext.text = "Yes";
                yes2text.text = "Yes";
                notext.text = "No";
                no2text.text = "No";
                QRtext.text = "Secret bonus";
                selectlanguagebut.text = "Language";
                swipetext.text = "Swipe";
                bye.text = "Bye";
                break;
            case 1: //Русский
                startext.text = "Звёзды: ";
                loses.text = "Проигрыши: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "Старт";
                optionstext.text = "Настройки";
                exittext.text = "Выход";
                exit2text.text = "Выйти?";
                deletealltext.text = "Сбросить прогресс";
                deleteall2text.text = "Сбросить прогресс?";
                musictext.text = "Музыка";
                yestext.text = "Да";
                yes2text.text = "Да";
                notext.text = "Нет";
                no2text.text = "Нет";
                QRtext.text = "Секретный бонус";
                selectlanguagebut.text = "Язык";
                swipetext.text = "Свайп";
                bye.text = "Пока";
                break;
            case 2: //Испанский
                startext.text = "Estrellas: ";
                loses.text = "Pérdidas: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "Comenzar";
                optionstext.text = "Configuraciones";
                exittext.text = "Salir";
                exit2text.text = "Salir?";
                deletealltext.text = "Restablecer progreso";
                deleteall2text.text = "Restablecer progreso?";
                musictext.text = "Música";
                yestext.text = "Sí";
                yes2text.text = "Sí";
                notext.text = "No";
                no2text.text = "No";
                QRtext.text = "Bono secreto";
                selectlanguagebut.text = "Idioma";
                swipetext.text = "Golpe fuerte";
                bye.text = "Adiós";
                break;
            case 3: //Французкий
                startext.text = "Étoiles: ";
                loses.text = "Pertes: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "Début";
                optionstext.text = "Paramètres";
                exittext.text = "Quitter";
                exit2text.text = "Quitter?";
                deletealltext.text = "Réinitialiser";
                deleteall2text.text = "Réinitialiser?";
                musictext.text = "Musique";
                yestext.text = "Oui";
                yes2text.text = "Oui";
                notext.text = "Non";
                no2text.text = "Non";
                QRtext.text = "Bonus secret";
                selectlanguagebut.text = "Langue";
                swipetext.text = "Balayer";
                bye.text = "Au revoir";
                break;
            case 4: //Итальянский
                startext.text = "Stelle: ";
                loses.text = "Perdite: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "Inizio";
                optionstext.text = "Impostazioni";
                exittext.text = "Uscita";
                exit2text.text = "Esci?";
                deletealltext.text = "Ripristina il progresso";
                deleteall2text.text = "Ripristina il progresso?";
                musictext.text = "Musica";
                yestext.text = "Sì";
                yes2text.text = "Sì";
                notext.text = "No";
                no2text.text = "No";
                QRtext.text = "Bonus segreto";
                selectlanguagebut.text = "Lingua";
                swipetext.text = "Rubare";
                bye.text = "Ciao";
                break;
            case 5: //Польский
                startext.text = "Gwiazdy: ";
                loses.text = "Straty: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "Zacznij";
                optionstext.text = "Ustawienia";
                exittext.text = "Wyjdź";
                exit2text.text = "Wyjdź?";
                deletealltext.text = "Zresetuj postęp";
                deleteall2text.text = "Zresetuj postęp?";
                musictext.text = "Muzyka";
                yestext.text = "Tak.";
                yes2text.text = "Tak.";
                notext.text = "Nie";
                no2text.text = "Nie";
                QRtext.text = "Tajna premia";
                selectlanguagebut.text = "Język";
                swipetext.text = "Trzepnąć";
                bye.text = "PA";
                break;
            case 6: //Турецкий
                startext.text = "Yıldız: ";
                loses.text = "Kayıplar: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "Başlangıç";
                optionstext.text = "Ayarlar";
                exittext.text = "Çıkış";
                exit2text.text = "Çıkış?";
                deletealltext.text = "İlerlemeyi sıfırla";
                deleteall2text.text = "İlerlemeyi sıfırla?";
                musictext.text = "Müzik";
                yestext.text = "Evet";
                yes2text.text = "Evet";
                notext.text = "Hayır";
                no2text.text = "Hayır";
                QRtext.text = "Gizli bonus";
                selectlanguagebut.text = "Dil";
                swipetext.text = "Tokatlamak";
                bye.text = "Hoşçakal";
                break;
            case 7: //Японский
                startext.text = "星: ";
                loses.text = "損失: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "スタート";
                optionstext.text = "設定";
                exittext.text = "出口";
                exit2text.text = "출구?";
                deletealltext.text = "進行状況をリセットする";
                deleteall2text.text = "進行状況をリセットする?";
                musictext.text = "音楽";
                yestext.text = "はい。";
                yes2text.text = "はい。";
                notext.text = "いいえ";
                no2text.text = "いいえ";
                QRtext.text = "秘密のボーナス";
                selectlanguagebut.text = "言語";
                swipetext.text = "スワイプ";
                bye.text = "さようなら";
                break;
            case 8: //Китайский
                startext.text = "明星: ";
                loses.text = "損失: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "啟動";
                optionstext.text = "設置";
                exittext.text = "出口";
                exit2text.text = "退出?";
                deletealltext.text = "重置進度";
                deleteall2text.text = "重置進度?";
                musictext.text = "音樂";
                yestext.text = "是的";
                yes2text.text = "是的";
                notext.text = "沒有";
                no2text.text = "沒有";
                QRtext.text = "秘密獎金";
                selectlanguagebut.text = "語言";
                swipetext.text = "刷卡";
                bye.text = "再見";
                break;
            case 9: //Корейский
                startext.text = "별: ";
                loses.text = "손실: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "시작";
                optionstext.text = "설정";
                exittext.text = "출구";
                exit2text.text = "출구?";
                deletealltext.text = "초기화 진행";
                deleteall2text.text = "초기화 진행?";
                musictext.text = "음악";
                yestext.text = "네.";
                yes2text.text = "네.";
                notext.text = "아니요";
                no2text.text = "아니요";
                QRtext.text = "비밀 보너스";
                selectlanguagebut.text = "언어";
                swipetext.text = "강타";
                bye.text = "안녕";
                break;
            case 10: //Бенгальский
                startext.text = "তারার: ";
                loses.text = "লোকসান: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "শুরু";
                optionstext.text = "সেটিংস";
                exittext.text = "প্রস্থান";
                exit2text.text = "প্রস্থান?";
                deletealltext.text = "অগ্রগতি পুনরায় সেট করুন";
                deleteall2text.text = "অগ্রগতি পুনরায় সেট করুন?";
                musictext.text = "সঙ্গীত";
                yestext.text = "হাঁ";
                yes2text.text = "হাঁ";
                notext.text = "না";
                no2text.text = "না";
                QRtext.text = "গোপন বোনাস";
                selectlanguagebut.text = "ভাষা";
                swipetext.text = "সোয়াইপ";
                bye.text = "বিদায়";
                break;
            case 11: //Венгерский
                startext.text = "Csillagok: ";
                loses.text = "Veszteség: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "Kezdet";
                optionstext.text = "Beállítások";
                exittext.text = "Kijárat";
                exit2text.text = "Kijárat?";
                deletealltext.text = "Állítsa be az előrehaladást";
                deleteall2text.text = "Állítsa be az előrehaladást?";
                musictext.text = "Zene";
                yestext.text = "Igen";
                yes2text.text = "Igen";
                notext.text = "Nincs";
                no2text.text = "Nincs";
                QRtext.text = "Titkos bónusz";
                selectlanguagebut.text = "Nyelv";
                swipetext.text = "Elcsór";
                bye.text = "Viszlát";
                break;
            case 12: //Вьетнамский
                startext.text = "Sao: ";
                loses.text = "Thiệt hại: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "Bắt đầu";
                optionstext.text = "Cài đặt";
                exittext.text = "Thoát";
                exit2text.text = "Thoát?";
                deletealltext.text = "Đặt lại tiến độ";
                deleteall2text.text = "Đặt lại tiến độ?";
                musictext.text = "Nhạc";
                yestext.text = "Vâng.";
                yes2text.text = "Vâng.";
                notext.text = "Không";
                no2text.text = "Không";
                QRtext.text = "Tiền thưởng bí mật";
                selectlanguagebut.text = "Ngôn ngữ";
                swipetext.text = "Vuốt";
                bye.text = "Tạm biệt";
                break;
            case 13: //Малайский
                startext.text = "Bintang: ";
                loses.text = "Kerugian: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "Mulakan";
                optionstext.text = "Tetapan";
                exittext.text = "Keluar";
                exit2text.text = "Keluar?";
                deletealltext.text = "Tetapkan semula kemajuan";
                deleteall2text.text = "Tetapkan semula kemajuan?";
                musictext.text = "Muzik";
                yestext.text = "Ya.";
                yes2text.text = "Ya.";
                notext.text = "Tidak";
                no2text.text = "Tidak";
                QRtext.text = "Bonus rahsia";
                selectlanguagebut.text = "Bahasa";
                swipetext.text = "Leret";
                bye.text = "Bye";
                break;
            case 14: //Немецкий
                startext.text = "Sterne: ";
                loses.text = "Verluste: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "Starten";
                optionstext.text = "Einstellungen";
                exittext.text = "Beenden";
                exit2text.text = "Abmelden?";
                deletealltext.text = "Fortschritt zurücksetzen";
                deleteall2text.text = "Fortschritt zurücksetzen?";
                musictext.text = "Musik";
                yestext.text = "Ja.";
                yes2text.text = "Ja.";
                notext.text = "Nein";
                no2text.text = "Nein";
                QRtext.text = "Geheimer Bonus";
                selectlanguagebut.text = "Sprache";
                swipetext.text = "Wischen";
                bye.text = "Tschüss";
                break;
            case 15: //Нидерландский
                startext.text = "Sterren: ";
                loses.text = "Verliezen: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "Begin";
                optionstext.text = "Instellingen";
                exittext.text = "Afrit";
                exit2text.text = "Afrit?";
                deletealltext.text = "Reset de voortgang";
                deleteall2text.text = "Reset de voortgang?";
                musictext.text = "Muziek";
                yestext.text = "Ja";
                yes2text.text = "Ja";
                notext.text = "Geen";
                no2text.text = "Geen";
                QRtext.text = "Geheime bonus";
                selectlanguagebut.text = "Taal";
                swipetext.text = "Wip";
                bye.text = "Doei";
                break;
            case 16: //Португальский
                startext.text = "Estrelas: ";
                loses.text = "Perdas: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "Comece";
                optionstext.text = "Configurações";
                exittext.text = "Sair";
                exit2text.text = "Sair?";
                deletealltext.text = "Repor o progresso";
                deleteall2text.text = "Repor o progresso?";
                musictext.text = "Música";
                yestext.text = "Sim.";
                yes2text.text = "Sim.";
                notext.text = "Não";
                no2text.text = "Não";
                QRtext.text = "Bônus secreto";
                selectlanguagebut.text = "Linguagem";
                swipetext.text = "Deslize";
                bye.text = "Tchau";
                break;
            case 17: //Хинди
                startext.text = "सितारों: ";
                loses.text = "हानि: " + PlayerPrefs.GetInt("Losses"); ;
                menu.TextScore();
                starttext.text = "प्रारंभ";
                optionstext.text = "सेटिंग्स";
                exittext.text = "निकास";
                exit2text.text = "निकास?";
                deletealltext.text = "प्रगति रीसेट करें";
                deleteall2text.text = "प्रगति रीसेट करें?";
                musictext.text = "संगीत";
                yestext.text = "हां";
                yes2text.text = "हां";
                notext.text = "नहीं";
                no2text.text = "नहीं";
                QRtext.text = "गुप्त बोनस";
                selectlanguagebut.text = "भाषा";
                swipetext.text = "कड़ी चोट";
                bye.text = "अलविदा";
                break;
        }

    }
}
